class FacetsTextTranslator
  def initialize
    @translation = {
        language: {
            A1: 'Afrikaans',
            A2: 'Albanian',
            A3: 'Amharic',
            A4: 'Arabic',
            A5: 'Armenian',
            A6: 'Ashanti',
            A7: 'Azeri',
            B1: 'Bantu',
            B2: 'Basque',
            B3: 'Bengali',
            B4: 'Bulgarian',
            B5: 'Burmese',
            C1: 'Chinese',
            C2: 'Comorian',
            C3: 'Czech',
            D1: 'Danish',
            D2: 'Dutch',
            D3: 'Dzongha',
            E1: 'English',
            E2: 'Estonian',
            F1: 'Farsi',
            F2: 'Finnish',
            F3: 'French',
            G1: 'Georgian',
            G2: 'German',
            G3: 'Ga',
            G4: 'Greek',
            H1: 'Hausa',
            H2: 'Hebrew',
            H3: 'Hindi',
            H4: 'Hungarian',
            I1: 'Icelandic',
            I2: 'Indonesian',
            I3: 'Italian',
            J1: 'Japanese',
            K1: 'Kazakh',
            K2: 'Khmer',
            K3: 'Kirghiz',
            K4: 'Korean',
            L1: 'Laotian',
            L2: 'Latvian',
            L3: 'Lithuanian',
            M1: 'Macedonian',
            M2: 'Malagasy',
            M3: 'Malay',
            M4: 'Moldavian',
            M5: 'Mongolian',
            N1: 'Nepali',
            N2: 'Norwegian',
            O1: 'Oromo',
            P1: 'Pashto',
            P2: 'Polish',
            P3: 'Portuguese',
            R1: 'Romanian',
            R2: 'Russian',
            S1: 'Samoan',
            S3: 'Sinhalese',
            S4: 'Slovakian',
            S5: 'Slovenian',
            S6: 'Somali',
            S7: 'Sotho',
            S8: 'Spanish',
            S9: 'Swahili',
            SA: 'Swazi',
            SB: 'Swedish',
            T1: 'Tagalog',
            T2: 'Tajik',
            T3: 'Thai',
            T4: 'Tibetan',
            T5: 'Tongan',
            T6: 'Turkish',
            T7: 'Turkmeni',
            T8: 'Tswana',
            UX: 'Unknown',
            U1: 'Urdu',
            U2: 'Uzbeki',
            V1: 'Vietnamese',
            X1: 'Xhosa',
            Z1: 'Zulu',
        },

    }
  end

  def translate(key, value)
    value = @translation[key.to_sym][value.capitalize.to_sym] if @translation.has_key?(key.to_sym)
    value
  end
end